---
roles:
  - name: geerlingguy.nginx
  - name: geerlingguy.mysql
  - name: gantsign.oh-my-zsh
  - name: ANXS.postgresql

collections:
  - name: community.general
  - name: kubernetes.core
    version: 1.2.1
  - name: operator_sdk.util
  - name: community.docker
  - name: awx.awx
